# Generated by Django 2.1.2 on 2018-12-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
