# Generated by Django 2.1.2 on 2018-12-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher_image'),
        ('courses', '0004_auto_20181224_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_konw',
            field=models.CharField(default='学习这门课程之前一定端正心态', max_length=100, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='主讲老师'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell_you',
            field=models.CharField(default='好好学习，天天向上', max_length=100, verbose_name='老师告诉你能学到什么'),
        ),
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟数）'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='视频地址'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构'),
        ),
    ]
